Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2022-12, with the labels that each got.

#6 Fix OVN migration job failing by adding checks for patch and condition to wait till machine config pods are in running state
  playbooks/roles/ocp-migration/tasks/sdn_to_ovnkube.yml
Labels: approved, lgtm, size/L

#24 Add infra_id to create cluster command
  playbooks/roles/hypershift/tasks/hypershift-install.yml
Labels: approved, lgtm, size/XS

#25 Fixing syslog and elastic search log forwarding
  playbooks/roles/ocp-cluster-logging/templates/clf-instance.yml.j2
Labels: approved, lgtm, size/S

#23 Update destroy log location
  playbooks/roles/hypershift/tasks/hypershift-destroy.yml
Labels: approved, lgtm, size/XS

#26 Updating the test cases for compliance operator
  playbooks/roles/ocp-compliance/README.md
  playbooks/roles/ocp-compliance/files/run-e2e.sh
  playbooks/roles/ocp-compliance/files/tests-cases.txt
Labels: approved, lgtm, size/M

#28 Descheduler deployment and running e2e test automation
  README.md
  examples/all.yaml
  examples/ocp_descheduler_vars.yaml
  playbooks/main.yml
  playbooks/ocp-descheduler.yml
  playbooks/roles/ocp-descheduler/README.md
  playbooks/roles/ocp-descheduler/defaults/main.yaml
  playbooks/roles/ocp-descheduler/tasks/main.yaml
  playbooks/roles/ocp-descheduler/vars/main.yml
Labels: approved, lgtm, size/L
