Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2022-11, with the labels that each got.

#19 Fix for OVNKube CNI role
  playbooks/roles/ocp-ovnkube-cni/tasks/egress-firewall.yml
  playbooks/roles/ocp-ovnkube-cni/tasks/networkpolicy.yml
Labels: approved, lgtm, size/M

#16 Adding compliance operator
  README.md
  ansible.cfg
  examples/all.yaml
  examples/ocp_compliance_vars.yaml
  playbooks/main.yml
  playbooks/ocp-compliance.yml
  playbooks/roles/ocp-compliance/README.md
  playbooks/roles/ocp-compliance/defaults/main.yml
  playbooks/roles/ocp-compliance/files/run-e2e.sh
  playbooks/roles/ocp-compliance/files/tests-cases.txt
  playbooks/roles/ocp-compliance/tasks/compliance-cleanup.yaml
  playbooks/roles/ocp-compliance/tasks/main.yml
  playbooks/roles/ocp-compliance/vars/main.yml
Labels: approved, lgtm, size/L

#20 Bug fix for compliance operator role
  playbooks/roles/ocp-compliance/tasks/main.yml
Labels: approved, lgtm, size/S

#22 Maintain playbooks ordering and structure changes
  README.md
Labels: approved, lgtm, size/M

#8 Hypershift deployment on PowerVS
  README.md
  examples/hypershift_destroy.yaml
  examples/hypershift_install.yaml
  group_vars/all.yml
  playbooks/hypershift.yml
  playbooks/main.yml
  playbooks/roles/hypershift/README.md
  playbooks/roles/hypershift/defaults/main.yml
  playbooks/roles/hypershift/tasks/hypershift-destroy.yml
  playbooks/roles/hypershift/tasks/hypershift-install.yml
  playbooks/roles/hypershift/tasks/main.yml
Labels: approved, lgtm, size/L

#21 IPA identity provider configuration and test automation
  README.md
  examples/all.yaml
  examples/ipa-identity-provider-vars.yaml
  playbooks/ipa-identity-provider.yml
  playbooks/main.yml
  playbooks/roles/ipa-identity-provider/README.md
  playbooks/roles/ipa-identity-provider/defaults/main.yaml
  playbooks/roles/ipa-identity-provider/tasks/main.yml
Labels: approved, lgtm, size/L

#9 QE parity feature: user defined project monitoring
  README.md
  examples/all.yaml
  examples/monitoring_user_defined_projects_vars.yaml
  playbooks/main.yml
  playbooks/monitoring-user-defined-projects.yml
  playbooks/roles/monitoring-user-defined-projects/README.md
  playbooks/roles/monitoring-user-defined-projects/defaults/main.yml
  playbooks/roles/monitoring-user-defined-projects/tasks/main.yml
Labels: approved, lgtm, size/L

#14 Automation for an identity provider- Request header
  README.md
  examples/all.yaml
  examples/request_header_identity_provider_vars.yaml
  playbooks/main.yml
  playbooks/request-header-identity-provider.yml
  playbooks/roles/request-header-identity-provider/README.md
  playbooks/roles/request-header-identity-provider/defaults/main.yml
  playbooks/roles/request-header-identity-provider/tasks/main.yml
Labels: approved, lgtm, size/L
