Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2023-08, with the labels that each got.

#53 MetalLB operator enablement in CI
  README.md
  examples/all.yaml
  examples/metallb_vars.yml
  playbooks/main.yml
  playbooks/ocp-metallb-operator.yml
  playbooks/roles/ocp-metallb-operator/README.md
  playbooks/roles/ocp-metallb-operator/defaults/main.yml
  playbooks/roles/ocp-metallb-operator/tasks/cleanup.yml
  playbooks/roles/ocp-metallb-operator/tasks/e2e.yml
  playbooks/roles/ocp-metallb-operator/tasks/install.yml
  playbooks/roles/ocp-metallb-operator/tasks/main.yml
  playbooks/roles/ocp-metallb-operator/tasks/operator-cleanup.yml
  playbooks/roles/ocp-metallb-operator/vars/main.yml
Labels: approved, lgtm, size/XXL, do-not-merge/contains-merge-commits

#56 Enhance metallb e2e tests code
  examples/all.yaml
  examples/metallb_vars.yml
  playbooks/roles/ocp-metallb-operator/README.md
  playbooks/roles/ocp-metallb-operator/defaults/main.yml
  playbooks/roles/ocp-metallb-operator/tasks/cleanup.yml
  playbooks/roles/ocp-metallb-operator/tasks/e2e.yml
  playbooks/roles/ocp-metallb-operator/tasks/install.yml
  playbooks/roles/ocp-metallb-operator/tasks/operator-cleanup.yml
Labels: approved, lgtm, size/L

#46 Enhancements for SDN to OVN-Kubernetes migration
  playbooks/roles/ocp-migration/tasks/sdn_to_ovnkube.yml
Labels: approved, lgtm, size/L

#57 Get Summary of e2e tests from command output
  playbooks/roles/ocp-e2e/tasks/main.yml
Labels: approved, lgtm, size/S

#58 summary issues- added expression to grep when e2e time in minutes
  playbooks/roles/ocp-e2e/tasks/main.yml
Labels: approved, lgtm, size/XS
