Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2024-12, with the labels that each got.

#82 Add support for Logging e2e testcases
  examples/all.yaml
  examples/ocp_logging_tests_private_e2e_vars.yaml
  playbooks/main.yml
  playbooks/ocp-logging-tests-private-e2e.yml
  playbooks/roles/ocp-logging-tests-private-e2e/README.md
  playbooks/roles/ocp-logging-tests-private-e2e/defaults/main.yml
  playbooks/roles/ocp-logging-tests-private-e2e/tasks/main.yml
  playbooks/roles/ocp-logging-tests-private-e2e/vars/main.yml
Labels: approved, lgtm, size/L

#92 Add additional approver/reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#97 remove common services feature
  README.md
  examples/all.yaml
  examples/cs_vars.yaml
  group_vars/all.yml
  playbooks/main.yml
  playbooks/ocp-cs.yml
  playbooks/roles/ocp-cs/README.md
  playbooks/roles/ocp-cs/defaults/main.yml
  playbooks/roles/ocp-cs/tasks/main.yml
  playbooks/roles/ocp-cs/templates/catalog-source.yaml.j2
  playbooks/roles/ocp-cs/templates/cs-group.yaml.j2
  playbooks/roles/ocp-cs/templates/cs-request.yaml.j2
  playbooks/roles/ocp-cs/templates/cs-sub.yaml.j2
Labels: approved, lgtm, size/L

#90 Add Hypershift agent based installation using ACM/MCE
  README.md
  examples/all.yaml
  examples/hypershift_agent.yaml
  playbooks/hypershift-agent.yml
  playbooks/main.yml
  playbooks/roles/hypershift-agent/README.md
  playbooks/roles/hypershift-agent/defaults/main.yml
  playbooks/roles/hypershift-agent/files/ConfigMap.yml
  playbooks/roles/hypershift-agent/files/RoleBinding.yml
  playbooks/roles/hypershift-agent/tasks/destroy.yml
  playbooks/roles/hypershift-agent/tasks/install.yml
  playbooks/roles/hypershift-agent/tasks/main.yml
  playbooks/roles/hypershift-agent/templates/agent-service-config.yaml.j2
  playbooks/roles/hypershift-agent/templates/cluster-image-set.yaml.j2
  playbooks/roles/hypershift-agent/vars/main.yaml
Labels: approved, lgtm, size/XL
