Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2024-05, with the labels that each got.

#68 fix e2e summary issue: Adding workaround for e2e summary issue.
  playbooks/roles/ocp-e2e/tasks/main.yml
Labels: approved, lgtm, size/M

#69 Update playbook to account for only 2 pods
  playbooks/roles/ocp-compliance/tasks/main.yml
Labels: approved, lgtm

#71 Enabling Network Obervability operator deployment and e2e tests run
  examples/all.yaml
  examples/ocp_network_observability_vars.yaml
  playbooks/main.yml
  playbooks/ocp-network-observability.yml
  playbooks/roles/ocp-network-observability/README.md
  playbooks/roles/ocp-network-observability/defaults/main.yml
  playbooks/roles/ocp-network-observability/files/ocp-qe-perfscale-ci-changes.patch
  playbooks/roles/ocp-network-observability/files/openshift-tests-private-changes.patch
  playbooks/roles/ocp-network-observability/tasks/cleanup.yaml
  playbooks/roles/ocp-network-observability/tasks/deployment.yml
  playbooks/roles/ocp-network-observability/tasks/e2e.yml
  playbooks/roles/ocp-network-observability/tasks/main.yml
  playbooks/roles/ocp-network-observability/templates/loki_deployment_log.txt.j2
  playbooks/roles/ocp-network-observability/templates/noo_deployment_log.txt.j2
  playbooks/roles/ocp-network-observability/vars/main.yml
Labels: approved, lgtm, size/XL

#72 Fixes and enhancements for CROO
  examples/all.yaml
  examples/cro_vars.yaml
  playbooks/roles/cluster-resource-override-operator/README.md
  playbooks/roles/cluster-resource-override-operator/defaults/main.yml
  playbooks/roles/cluster-resource-override-operator/tasks/main.yml
Labels: approved, lgtm, size/M
