Repository ocp-power-automation/ocp4-playbooks-extras, pull requests merged in 2025-03, with the labels that each got.

#103 scheduler-plugins automation changes
  README.md
  examples/all.yaml
  examples/scheduler-plugins.yaml
  playbooks/main.yml
  playbooks/roles/scheduler-plugins/README.md
  playbooks/roles/scheduler-plugins/defaults/main.yml
  playbooks/roles/scheduler-plugins/tasks/capacity_scheduler_plugin.yml
  playbooks/roles/scheduler-plugins/tasks/co_scheduling_plugin.yml
  playbooks/roles/scheduler-plugins/tasks/main.yml
  playbooks/roles/scheduler-plugins/tasks/node_resources_allocatable_plugin.yml
  playbooks/roles/scheduler-plugins/tasks/scheduler_plugins_setup.yml
  playbooks/roles/scheduler-plugins/vars/main.yml
  playbooks/scheduler-plugins.yml
Labels: approved, lgtm, size/L

#105 Ingress Firewall Operator Automation
  README.md
  examples/all.yaml
  examples/ocp_ingress_vars.yaml
  playbooks/main.yml
  playbooks/ocp-ingress-firewall-operator.yml
  playbooks/roles/ocp-ingress-firewall-operator/README.md
  playbooks/roles/ocp-ingress-firewall-operator/default/main.yaml
  playbooks/roles/ocp-ingress-firewall-operator/files/run-e2e.sh
  playbooks/roles/ocp-ingress-firewall-operator/tasks/main.yaml
  playbooks/roles/ocp-ingress-firewall-operator/vars/main.yml
Labels: approved, lgtm, size/L

#107 Fix minor bug in ocp-operator-api role
  playbooks/roles/ocp-operator-api/tasks/cleanup.yaml
  playbooks/roles/ocp-operator-api/tasks/install.yaml
Labels: approved, lgtm, size/S

#104 code changes for automation of cmo
  examples/all.yaml
  examples/ocp_cost_management_vars.yaml
  playbooks/ocp-cost-management.yml
  playbooks/roles/ocp-cost-management/README.md
  playbooks/roles/ocp-cost-management/defaults/main.yml
  playbooks/roles/ocp-cost-management/tasks/cmo-cleanup.yml
  playbooks/roles/ocp-cost-management/tasks/cmo-setup.yml
  playbooks/roles/ocp-cost-management/tasks/cmo-test.yml
  playbooks/roles/ocp-cost-management/tasks/main.yml
  playbooks/roles/ocp-cost-management/vars/main.yml
Labels: approved, lgtm, size/L

#108 Removing unnecessary until condition
  playbooks/roles/ocp-nfd-operator/tasks/main.yml
Labels: approved, lgtm, size/XS
